### ISSUE TITLE
Page 2 code issues

### ISSUE THREAD

**Issue by petewnr** [TrevH/Soundscape#11]
There are a few issues in the code of Page 2 in the branch website-code-v2:

1. A .row is created then .col-*-12, then another .row then .content-section .row then the .col-*-3 .col-*-6 .col-*-3: The first .row .col-*-12 are unnecessary

2. There are a lot of divs that are not necessary for example: there is

<div>
<figure>
</figure>
</div>

I don't think the div is necessary.

3. I don't know why we have created .figure-caption when bootstrap already has .figure - if there is a reason for creating an additional class/style then please let me know.

4. We also should be using the bootstrap .border and .border-*-0 to add and remove borders

This is about using the framework correctly.  Practice for the real world.

**Comment by shiva007oct** [comment]
1. Resolved. Removed the first row and col.

3. Figure-caption class adds caption styling of making the text grey. It could be done without it as well, can use a div tag or a paragraph tag but will need to add the effect on CSS otherwise. I read up that on Bootstrap4> content>figures.

4. Border resolved

**Comment by petewnr** [comment]
Check bootstrap to find an existing class to change the text to grey

**Comment by petewnr** [comment]
Also, I don't think you need to add the font-family to so many elements.  Can you just add it to body so that it applies to everything.  Then add your second font specifically to the menu content?

**Comment by petewnr** [comment]
Also can you please commit your most recent code so I can have a look at it.

**Comment by shiva007oct** [comment]
Changed text to grey with text-muted class. Also replaced figurecaption tag and class with a paragraph tag with text - muted class. 

Applied font family to the whole body

code committed
