### ISSUE TITLE
Page 2 navigation

### ISSUE THREAD

**Issue by TrevH** [TrevH/Soundscape#7]
Use bootstrap dropdown links to create the navigation to the relevant pages.

**Comment by TrevH** [comment]
Home link should use the word"Soundscape" 
Use the class active - people can see which page they are currently on
Remove existing NEXT link
figure caption under the picture and styled properly - check bootstrap for style of figcap
Image doesn't need a "click here"
First column - needs title - text "abstract"
Move down the container down to give some space under the nav bar

**Comment by shiva007oct** [comment]
Changed home link to soundscape
Class active used
Next link removed
Figure caption added and styled properly 
Click here button removed
Abstract text title added
Space under navbar provided

**Comment by shiva007oct** [comment]
Use 'Barlow Condensed' for navigation Brand named "soundscape" and also the navbar links.

Link in HTML:
link href="https://fonts.googleapis.com/css?family=Barlow+Condensed" rel="stylesheet">

Use in CSS
font-family: 'Barlow Condensed', sans-serif;
