### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by TrevH** [TrevH/Soundscape#8]
Use google font decide the font family and import across the document

**Comment by TrevH** [comment]
Page 2 - left column needs "title"
text - smaller and italics
middle column different style
Check the amount of padding around the text to separate each and looking elegant

**Comment by shiva007oct** [comment]
--------
Use 'Barlow Condensed' for navigation Brand named "soundscape" and also the navbar links.

Link in HTML:
link href="https://fonts.googleapis.com/css?family=Barlow+Condensed" rel="stylesheet">

Use in CSS
font-family: 'Barlow Condensed', sans-serif;

### **FIXES:**
Navbar font changed for page2 : Title font changed to match theme
------

Use Helvertica font for body text

In CSS
font-family: Helvetica Neue,Helvetica,Arial,sans-serif; 

### **FIXES:**
content font changed for page2
--------

### **FIXES:**
Page 2 title fixed Abstract can be replaced with title name
Text - smaller and italics fixed
Middle column style fixed
Amount of padding fixed
Border on the right fixed similar to Diana's site
